apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bankapp-pvc
  namespace: bankapp
spec:
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
