kind: Secret
apiVersion: v1
metadata:
  name: bankapp-secret
  namespace: bankapp
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: VGVzdEAxMjM=  # Base64 encoded value of 'Test@123'
  MYSQL_DATABASE: QmFua0RC  # Base64 encoded value of 'BankDB'