name: DevSecOpsCI

on:
    push:
        branches: [ DevOps ]

jobs:
    Code-Quality:
        uses: ./.github/workflows/code-quality.yml
    Secret-Scanning:
        uses: ./.github/workflows/secret-scanning.yml
