name: DevSecOpsCI

on:
    push:
        branches: [ DevOps ]

jobs:
    Code-Quality:
        uses: ./.github/workflows/code-lint.yml
    Secret-Scanning:
        uses: ./.github/workflows/secret-scanning.yml
    #Dependency-Scanning:
    #    uses: ./.github/workflows/dependency-scan.yml
    Docker-Scans:
        uses: ./.github/workflows/docker-scans.yml
        secrets: inherit
    Sonar-Scan:
        uses: ./.github/workflows/sonar-scan.yml
        secrets: inherit
    Image-Push:
        needs: [Code-Quality, Secret-Scanning, Docker-Scans, Sonar-Scan]
        uses: ./.github/workflows/image-push.yml
        secrets: inherit
    Deploy:
        needs: [Code-Quality, Secret-Scanning, Docker-Scans, Sonar-Scan, Image-Push]
        uses: ./.github/workflows/deploy.yml
        secrets: inherit