name: SecretScanning
on:
    workflow_call:

jobs:
    secret-scanning:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0 # Fetches all git history to catch hidden secrets in old commits

        - name: Run TruffleHog Secret Scan
          uses: trufflesecurity/trufflehog@main
          with:
            extra_args: --only-verified